convolution_layers_count:
  - 3
  - 5
dense_layers_units:
  - [1000, 500]
epoch_count:
  - 10
data_filename:
  -  - "Data"
     - "2_Extracted"
     - "Amazon_5.csv"
threshold_fall:
  - -0.00067
threshold_rise:
  - 0.00047
learning_rate:
  - 0.0001
test_ratio:
  - 0.07
validation_ratio:
  - 0.05
feature_to_predict_num:
  - 3
balance_training_dataset:
  - True
batch_size:
  - null
metrics:
  - - "f1_m"
callbacks:
  - - "f1_weighted"
    - "confusion_matrix"
    - "predictions"
# early_stopping_params:
#   - monitor: "val_loss"
#     mode: "min"
#     min_delta: 0.001
#     patience: 500
#     start_from_epoch: 300




